name: Repo Push Mail Alert

on:
  schedule:
    - cron: "*/5 * * * *"   # runs every 5 minutes
  push:
    branches:
      - main

jobs:
  send-mail:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub  TEST Alert"
          to: ${{ secrets.EMAIL_TO }}
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Code pushed to repository

            Repository: ${{ github.repository }}
            User: ${{ github.actor }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
